apiVersion: v2
appVersion: v1.9.0-cap-CR-22221
description: A Helm chart for Argo Events, the event-driven workflow automation framework
name: argo-events
version: 2.4.2-1-cap-CR-22221
home: https://github.com/argoproj/argo-helm
icon: https://argoproj.github.io/argo-events/assets/logo.png
keywords:
  - argoproj
  - argo-events
sources:
  - https://github.com/argoproj/argo-events
maintainers:
  - name: argoproj
    url: https://argoproj.github.io/
annotations:
  artifacthub.io/changes: |
    - "[Added]: Ability to specify port for webhook deployment"
